name: Deployment Test
on:
  push:
    branches:
      - master
env:
  RUNNER_PATH: ${{ github.workspace }}
  DEPLOY_PATH: /opt/my-super-project
jobs:
  checkout:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          docker-compose.yml
        sparse-checkout-cone-mode: false
    - name: Print some vars
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Runner path: " ${{ env.RUNNER_PATH }}
        echo "Deploy path: " ${{ env.DEPLOY_PATH }}
    - name: Print file list && owners
      run: sudo ls -la .
  deploy:
    needs: checkout
    runs-on: [self-hosted]
    steps:
    - name: Deploy docker compose file to server work dir
      run: |
        sudo rsync -av --ignore-times ./docker-compose.yml ${{ env.DEPLOY_PATH }}
  run:
    needs: deploy
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ${{ env.DEPLOY_PATH }}
    steps:
    - name: Check current directory
      run: |
        sudo pwd
