name: Deployment Test

on:
  push:
    branches:
      - master

env:
  DEPLOY_PATH: /opt/my-super-project
  RUNNER_PATH: ${{ github.workspace }}

jobs:
  checkout:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          docker-compose.yml
        sparse-checkout-cone-mode: false
    - name: Print current branch
      run: |
        echo "Current branch: ${{ github.ref }}"
        echo "Runner work path: " ${{ env.RUNNER_PATH }}
        echo "Deploy path: " ${{ env.DEPLOY_PATH }}
    - name: Print file list && owners
      run: ls -la .

  deploy:
    needs: checkout
    runs-on: [self-hosted]
    steps:
    - name: Deploy docker compose file to server
      run: |
        sudo rsync -av ./docker-compose.yml ${{ env.DEPLOY_PATH }}
  
  run:
    needs: deploy
    runs-on: [self-hosted]
    steps:
    - name: Run new config on server
      working-directory: ${{ env.DEPLOY_PATH }}
      run: |
        sudo pwd
